travis:
  secure:
    BINSTAR_TOKEN: f5tIQrHUHrJPD8inv54CLtT4a47wUiN2pENki2Mzdo3PLul+v49zMik5wR7D43JpPS5eVqs6dQYlfG72THunR7P4oUV6i/jPbAllJv/Vax3UMmAtq8rMcKjvqupRY+7rz1A7TzdmXDkXmaUp/QMNqTuYoGmULqwUulcVw7UR/f2t72Wj85XVX7ccy3DCYNCQMVwaC76JLTc5vMu9TWYvgAIb7afaaxwNqqOqMsWZdwGkj5i7I/kia7oGm7p7MeERfEmQPx7/Toy1xbL/ZDUnjXzplvqAnii8FDq2Tq9F+K7kSBL3jOgmmFimR7NVuNZA2hvgRnI8nlY4TTAJlfle5yQufR4allSIW9i1AZUzz8DXWRiFIsEixemNwdsDR4n0HEN0c+wfzkMbK+TKze2pVtobgbBrLC+mPv9zTR4xfpmK9F7pVUtkZELTHUghF8OYrrETr4WqbEDFHdMmg1eAxcx9uHmUJi9RWkWTa1RJQown090rhzTOJhxu5OXbX1jIJsB05AliSmTBiuRp7ev5ZQ98E2af7BgziOjfMBYpc1jXvloFyo0g68h5r3n+PBuPXSg4SXLi93DZpjVlE+knqyAIh6bPBRA8mB5F2SBWLt82tez3NXyK3V7sU3tr6/knpwJAX0aMXfJOV4ZZU9goryOijXiMj42STYCjHXrbrqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
